# -*- coding: utf-8 -*-
"""atividade 18 - 15/06/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PyxjuFlE-ymbUZowZ3xVo4RsHQy-Tep8
"""

matriz = [ [1, 2, 3, 4, 0],
           [4, 3, 2, 1, 0],
           [1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2],
           [3, 3, 3, 3, 3]]
print(matriz)

matriz = [ [1, 2, 3, 4, 0],
           [4, 3, 2, 1, 0],
           [1, 1, 142312, 1, 1],
           [2, 2, 2, 2, 2],
           [3, 3, 3, 3, 3]]

for i in range(4):
  for j in range(4):
    print(matriz[i][j], end = " ")

matriz[2][2]